spring.application.name=student-course-management

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/student_course_management_db
spring.datasource.username=postgres
spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql

#security config
#spring.security.user.name = mandip
#spring.security.user.password = pass

jwt.secretKey=dsgf45gsdsvdv56w4ges45fds5adsf5adsg4ds5g5dsgvds2vdcxvds5f45dsg5465dsgsd2dsgv5ds

# for auth2 authentication:

#spring.security.oauth2.client.registration.google.client-id=aslfjdlas
#spring.security.oauth2.client.registration.google.client-secret=
